default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: developer_community_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: developer_community_test
  pool: 5
  username: postgres
  password: postgres

